-- Migration: 0002_create_identifier_words.sql
-- Curated bilingual word lists used by the generate-identifier Edge Function.
-- Each profile gets one [Adjective][Noun][NN-NNNN] anonymous identifier.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.identifier_words;
--   DROP TYPE  IF EXISTS public.word_kind;
--
-- TODO i18n review: Swedish word lists must be reviewed by a native Swedish speaker
-- before this migration ships to production. Mark reviewed with:
--   -- reviewed by [name] on YYYY-MM-DD

-- ---------------------------------------------------------------------------
-- Types + Table
-- ---------------------------------------------------------------------------

CREATE TYPE public.word_kind AS ENUM ('adjective', 'noun');

CREATE TABLE public.identifier_words (
  id       bigserial       PRIMARY KEY,
  word     text            NOT NULL,
  kind     public.word_kind NOT NULL,
  language text            NOT NULL CHECK (language IN ('sv', 'en')),
  UNIQUE (word, kind, language),
  approved boolean         NOT NULL DEFAULT true
);

-- Hot-path lookup: pick random approved adjective/noun for a given language.
CREATE INDEX identifier_words_lookup_idx
  ON public.identifier_words (kind, language, approved)
  WHERE approved = true;

-- ---------------------------------------------------------------------------
-- RLS — public read, service-role write only
-- ---------------------------------------------------------------------------

ALTER TABLE public.identifier_words ENABLE ROW LEVEL SECURITY;

CREATE POLICY "identifier_words are publicly readable"
  ON public.identifier_words FOR SELECT
  USING (true);

-- No INSERT / UPDATE / DELETE policies → only service_role can write.

-- ---------------------------------------------------------------------------
-- Seed data — English adjectives (~100)
-- TODO i18n review: English list — review by founder before production
-- ---------------------------------------------------------------------------

INSERT INTO public.identifier_words (word, kind, language) VALUES
  -- Positive qualities
  ('Amber',    'adjective', 'en'),
  ('Bright',   'adjective', 'en'),
  ('Calm',     'adjective', 'en'),
  ('Clear',    'adjective', 'en'),
  ('Crisp',    'adjective', 'en'),
  ('Daring',   'adjective', 'en'),
  ('Deep',     'adjective', 'en'),
  ('Early',    'adjective', 'en'),
  ('Earnest',  'adjective', 'en'),
  ('Even',     'adjective', 'en'),
  ('Fair',     'adjective', 'en'),
  ('Firm',     'adjective', 'en'),
  ('Frank',    'adjective', 'en'),
  ('Gentle',   'adjective', 'en'),
  ('Golden',   'adjective', 'en'),
  ('Grand',    'adjective', 'en'),
  ('Honest',   'adjective', 'en'),
  ('Hopeful',  'adjective', 'en'),
  ('Humble',   'adjective', 'en'),
  ('Keen',     'adjective', 'en'),
  ('Kind',     'adjective', 'en'),
  ('Lasting',  'adjective', 'en'),
  ('Lively',   'adjective', 'en'),
  ('Loyal',    'adjective', 'en'),
  ('Mellow',   'adjective', 'en'),
  ('Mild',     'adjective', 'en'),
  ('Nimble',   'adjective', 'en'),
  ('Noble',    'adjective', 'en'),
  ('Open',     'adjective', 'en'),
  ('Patient',  'adjective', 'en'),
  ('Polished', 'adjective', 'en'),
  ('Pure',     'adjective', 'en'),
  ('Quiet',    'adjective', 'en'),
  ('Radiant',  'adjective', 'en'),
  ('Ready',    'adjective', 'en'),
  ('Serene',   'adjective', 'en'),
  ('Sharp',    'adjective', 'en'),
  ('Silver',   'adjective', 'en'),
  ('Simple',   'adjective', 'en'),
  ('Sincere',  'adjective', 'en'),
  ('Slender',  'adjective', 'en'),
  ('Smart',    'adjective', 'en'),
  ('Smooth',   'adjective', 'en'),
  ('Soft',     'adjective', 'en'),
  ('Solid',    'adjective', 'en'),
  ('Steady',   'adjective', 'en'),
  ('Stellar',  'adjective', 'en'),
  ('Still',    'adjective', 'en'),
  ('Sturdy',   'adjective', 'en'),
  ('Subtle',   'adjective', 'en'),
  ('Swift',    'adjective', 'en'),
  ('Tender',   'adjective', 'en'),
  ('Thankful', 'adjective', 'en'),
  ('Thorough', 'adjective', 'en'),
  ('Tidy',     'adjective', 'en'),
  ('Timely',   'adjective', 'en'),
  ('True',     'adjective', 'en'),
  ('Trusted',  'adjective', 'en'),
  ('Valiant',  'adjective', 'en'),
  ('Vibrant',  'adjective', 'en'),
  ('Vivid',    'adjective', 'en'),
  ('Warm',     'adjective', 'en'),
  ('Witty',    'adjective', 'en'),
  ('Worthy',   'adjective', 'en'),
  -- Nature / colour inspired
  ('Arctic',   'adjective', 'en'),
  ('Auburn',   'adjective', 'en'),
  ('Azure',    'adjective', 'en'),
  ('Cobalt',   'adjective', 'en'),
  ('Copper',   'adjective', 'en'),
  ('Coral',    'adjective', 'en'),
  ('Crimson',  'adjective', 'en'),
  ('Crystal',  'adjective', 'en'),
  ('Dusk',     'adjective', 'en'),
  ('Emerald',  'adjective', 'en'),
  ('Fern',     'adjective', 'en'),
  ('Flint',    'adjective', 'en'),
  ('Frost',    'adjective', 'en'),
  ('Hazel',    'adjective', 'en'),
  ('Indigo',   'adjective', 'en'),
  ('Ivory',    'adjective', 'en'),
  ('Jade',     'adjective', 'en'),
  ('Lunar',    'adjective', 'en'),
  ('Maple',    'adjective', 'en'),
  ('Misty',    'adjective', 'en'),
  ('Mossy',    'adjective', 'en'),
  ('Opal',     'adjective', 'en'),
  ('Pine',     'adjective', 'en'),
  ('Russet',   'adjective', 'en'),
  ('Sandy',    'adjective', 'en'),
  ('Scarlet',  'adjective', 'en'),
  ('Slate',    'adjective', 'en'),
  ('Solar',    'adjective', 'en'),
  ('Tawny',    'adjective', 'en'),
  ('Teal',     'adjective', 'en'),
  ('Umber',    'adjective', 'en'),
  ('Violet',   'adjective', 'en'),
  ('Willow',   'adjective', 'en'),
  ('Wintry',   'adjective', 'en');

-- ---------------------------------------------------------------------------
-- Seed data — English nouns (~100)
-- TODO i18n review: English list — review by founder before production
-- ---------------------------------------------------------------------------

INSERT INTO public.identifier_words (word, kind, language) VALUES
  -- Animals
  ('Badger',    'noun', 'en'),
  ('Bear',      'noun', 'en'),
  ('Beaver',    'noun', 'en'),
  ('Crane',     'noun', 'en'),
  ('Deer',      'noun', 'en'),
  ('Dove',      'noun', 'en'),
  ('Eagle',     'noun', 'en'),
  ('Elk',       'noun', 'en'),
  ('Falcon',    'noun', 'en'),
  ('Finch',     'noun', 'en'),
  ('Fox',       'noun', 'en'),
  ('Hare',      'noun', 'en'),
  ('Hawk',      'noun', 'en'),
  ('Heron',     'noun', 'en'),
  ('Jay',       'noun', 'en'),
  ('Kestrel',   'noun', 'en'),
  ('Lark',      'noun', 'en'),
  ('Lynx',      'noun', 'en'),
  ('Martin',    'noun', 'en'),
  ('Merlin',    'noun', 'en'),
  ('Mink',      'noun', 'en'),
  ('Mole',      'noun', 'en'),
  ('Moose',     'noun', 'en'),
  ('Moth',      'noun', 'en'),
  ('Otter',     'noun', 'en'),
  ('Owl',       'noun', 'en'),
  ('Puffin',    'noun', 'en'),
  ('Robin',     'noun', 'en'),
  ('Rook',      'noun', 'en'),
  ('Seal',      'noun', 'en'),
  ('Shrike',    'noun', 'en'),
  ('Sparrow',   'noun', 'en'),
  ('Starling',  'noun', 'en'),
  ('Stork',     'noun', 'en'),
  ('Swan',      'noun', 'en'),
  ('Swift',     'noun', 'en'),
  ('Teal',      'noun', 'en'),
  ('Vole',      'noun', 'en'),
  ('Wagtail',   'noun', 'en'),
  ('Weasel',    'noun', 'en'),
  ('Wolf',      'noun', 'en'),
  ('Wren',      'noun', 'en'),
  -- Nature / objects
  ('Acorn',     'noun', 'en'),
  ('Anchor',    'noun', 'en'),
  ('Ash',       'noun', 'en'),
  ('Birch',     'noun', 'en'),
  ('Brook',     'noun', 'en'),
  ('Cedar',     'noun', 'en'),
  ('Cliff',     'noun', 'en'),
  ('Cloud',     'noun', 'en'),
  ('Clover',    'noun', 'en'),
  ('Compass',   'noun', 'en'),
  ('Creek',     'noun', 'en'),
  ('Dune',      'noun', 'en'),
  ('Fern',      'noun', 'en'),
  ('Field',     'noun', 'en'),
  ('Fjord',     'noun', 'en'),
  ('Flint',     'noun', 'en'),
  ('Forest',    'noun', 'en'),
  ('Garden',    'noun', 'en'),
  ('Glen',      'noun', 'en'),
  ('Grove',     'noun', 'en'),
  ('Harbor',    'noun', 'en'),
  ('Heath',     'noun', 'en'),
  ('Hollow',    'noun', 'en'),
  ('Island',    'noun', 'en'),
  ('Knoll',     'noun', 'en'),
  ('Lake',      'noun', 'en'),
  ('Lantern',   'noun', 'en'),
  ('Larch',     'noun', 'en'),
  ('Ledge',     'noun', 'en'),
  ('Maple',     'noun', 'en'),
  ('Marsh',     'noun', 'en'),
  ('Meadow',    'noun', 'en'),
  ('Moor',      'noun', 'en'),
  ('Mossberg',  'noun', 'en'),
  ('Peak',      'noun', 'en'),
  ('Pebble',    'noun', 'en'),
  ('Pine',      'noun', 'en'),
  ('Pond',      'noun', 'en'),
  ('Ridge',     'noun', 'en'),
  ('River',     'noun', 'en'),
  ('Rock',      'noun', 'en'),
  ('Shore',     'noun', 'en'),
  ('Slope',     'noun', 'en'),
  ('Spring',    'noun', 'en'),
  ('Stone',     'noun', 'en'),
  ('Stream',    'noun', 'en'),
  ('Thorn',     'noun', 'en'),
  ('Tide',      'noun', 'en'),
  ('Trail',     'noun', 'en'),
  ('Valley',    'noun', 'en'),
  ('Willow',    'noun', 'en'),
  ('Wood',      'noun', 'en');

-- ---------------------------------------------------------------------------
-- Seed data — Swedish adjectives (~100)
-- TODO i18n review: Swedish list — MUST be reviewed by native Swedish speaker
-- ---------------------------------------------------------------------------

INSERT INTO public.identifier_words (word, kind, language) VALUES
  ('Aktiv',     'adjective', 'sv'),
  ('Balanserad','adjective', 'sv'),
  ('Blid',      'adjective', 'sv'),
  ('Bredsinnad','adjective', 'sv'),
  ('Chill',     'adjective', 'sv'),
  ('Djup',      'adjective', 'sv'),
  ('Driftig',   'adjective', 'sv'),
  ('Enkel',     'adjective', 'sv'),
  ('Ärlig',     'adjective', 'sv'),
  ('Fast',      'adjective', 'sv'),
  ('Fin',       'adjective', 'sv'),
  ('Frimodig',  'adjective', 'sv'),
  ('Genomtänkt','adjective', 'sv'),
  ('Glad',      'adjective', 'sv'),
  ('Grundlig',  'adjective', 'sv'),
  ('Harmonisk', 'adjective', 'sv'),
  ('Hoppfull',  'adjective', 'sv'),
  ('Inspirerad','adjective', 'sv'),
  ('Ivrig',     'adjective', 'sv'),
  ('Klar',      'adjective', 'sv'),
  ('Klok',      'adjective', 'sv'),
  ('Kraftfull', 'adjective', 'sv'),
  ('Lättill',   'adjective', 'sv'),
  ('Levande',   'adjective', 'sv'),
  ('Lojal',     'adjective', 'sv'),
  ('Lugn',      'adjective', 'sv'),
  ('Mild',      'adjective', 'sv'),
  ('Mjuk',      'adjective', 'sv'),
  ('Modig',     'adjective', 'sv'),
  ('Munter',    'adjective', 'sv'),
  ('Nyfiken',   'adjective', 'sv'),
  ('Omsorgsfull','adjective','sv'),
  ('Omtänksam', 'adjective', 'sv'),
  ('Ordentlig', 'adjective', 'sv'),
  ('Pålitlig',  'adjective', 'sv'),
  ('Rak',       'adjective', 'sv'),
  ('Rask',      'adjective', 'sv'),
  ('Respektfull','adjective','sv'),
  ('Rolig',     'adjective', 'sv'),
  ('Rättvis',   'adjective', 'sv'),
  ('Snäll',     'adjective', 'sv'),
  ('Stabil',    'adjective', 'sv'),
  ('Stark',     'adjective', 'sv'),
  ('Stillsam',  'adjective', 'sv'),
  ('Stolt',     'adjective', 'sv'),
  ('Sympatisk', 'adjective', 'sv'),
  ('Taktfull',  'adjective', 'sv'),
  ('Tillförlitlig','adjective','sv'),
  ('Trygg',     'adjective', 'sv'),
  ('Uppmärksam','adjective', 'sv'),
  ('Uppriktig', 'adjective', 'sv'),
  ('Varsam',    'adjective', 'sv'),
  ('Varm',      'adjective', 'sv'),
  ('Vettig',    'adjective', 'sv'),
  ('Viljestark','adjective', 'sv'),
  ('Vis',       'adjective', 'sv'),
  ('Vänlig',    'adjective', 'sv'),
  ('Välbalanserad','adjective','sv'),
  ('Välmenande','adjective', 'sv'),
  ('Äkta',      'adjective', 'sv'),
  -- Nature/colour inspired (Swedish)
  ('Arktisk',   'adjective', 'sv'),
  ('Azurblå',   'adjective', 'sv'),
  ('Bärnstensfärgad','adjective','sv'),
  ('Bergfast',  'adjective', 'sv'),
  ('Björkgrön', 'adjective', 'sv'),
  ('Blågrå',    'adjective', 'sv'),
  ('Bronsfärgad','adjective','sv'),
  ('Dimmig',    'adjective', 'sv'),
  ('Frostig',   'adjective', 'sv'),
  ('Gyllene',   'adjective', 'sv'),
  ('Havsvid',   'adjective', 'sv'),
  ('Isblå',     'adjective', 'sv'),
  ('Jadegrön',  'adjective', 'sv'),
  ('Kopparbrun','adjective', 'sv'),
  ('Krispig',   'adjective', 'sv'),
  ('Lövgrön',   'adjective', 'sv'),
  ('Mossfärgad','adjective', 'sv'),
  ('Silvrig',   'adjective', 'sv'),
  ('Skogig',    'adjective', 'sv'),
  ('Snövit',    'adjective', 'sv'),
  ('Solklar',   'adjective', 'sv'),
  ('Stengrå',   'adjective', 'sv'),
  ('Stormig',   'adjective', 'sv'),
  ('Tallgrön',  'adjective', 'sv'),
  ('Vattenblå', 'adjective', 'sv'),
  ('Vinröd',    'adjective', 'sv'),
  ('Vinterkall','adjective', 'sv'),
  ('Violett',   'adjective', 'sv'),
  ('Äppelgrön', 'adjective', 'sv'),
  ('Ödemarksgrå','adjective','sv');

-- ---------------------------------------------------------------------------
-- Seed data — Swedish nouns (~100)
-- TODO i18n review: Swedish list — MUST be reviewed by native Swedish speaker
-- ---------------------------------------------------------------------------

INSERT INTO public.identifier_words (word, kind, language) VALUES
  -- Animals (Swedish names)
  ('Bäver',     'noun', 'sv'),
  ('Björn',     'noun', 'sv'),
  ('Blåmes',    'noun', 'sv'),
  ('Ekorre',    'noun', 'sv'),
  ('Eld',       'noun', 'sv'),
  ('Falk',      'noun', 'sv'),
  ('Fjäril',    'noun', 'sv'),
  ('Grävling',  'noun', 'sv'),
  ('Gråsparv',  'noun', 'sv'),
  ('Hare',      'noun', 'sv'),
  ('Hermelin',  'noun', 'sv'),
  ('Hjort',     'noun', 'sv'),
  ('Igelkott',  'noun', 'sv'),
  ('Järv',      'noun', 'sv'),
  ('Korp',      'noun', 'sv'),
  ('Lärka',     'noun', 'sv'),
  ('Lodjur',    'noun', 'sv'),
  ('Lom',       'noun', 'sv'),
  ('Mård',      'noun', 'sv'),
  ('Mink',      'noun', 'sv'),
  ('Mås',       'noun', 'sv'),
  ('Nattskärra','noun', 'sv'),
  ('Näktergal', 'noun', 'sv'),
  ('Orm',       'noun', 'sv'),
  ('Otter',     'noun', 'sv'),
  ('Pilgrimsfalk','noun', 'sv'),
  ('Räv',       'noun', 'sv'),
  ('Ripan',     'noun', 'sv'),
  ('Rördrom',   'noun', 'sv'),
  ('Skata',     'noun', 'sv'),
  ('Snöuggla',  'noun', 'sv'),
  ('Stenfalk',  'noun', 'sv'),
  ('Storspov',  'noun', 'sv'),
  ('Svalan',    'noun', 'sv'),
  ('Svan',      'noun', 'sv'),
  ('Tornfalk',  'noun', 'sv'),
  ('Trast',     'noun', 'sv'),
  ('Uggla',     'noun', 'sv'),
  ('Uttrar',    'noun', 'sv'),
  ('Varg',      'noun', 'sv'),
  ('Vessla',    'noun', 'sv'),
  ('Vildsvin',  'noun', 'sv'),
  -- Nature / objects (Swedish)
  ('Alen',      'noun', 'sv'),
  ('Älv',       'noun', 'sv'),
  ('Backe',     'noun', 'sv'),
  ('Bäck',      'noun', 'sv'),
  ('Berg',      'noun', 'sv'),
  ('Björk',     'noun', 'sv'),
  ('Bok',       'noun', 'sv'),
  ('Brygga',    'noun', 'sv'),
  ('Dal',       'noun', 'sv'),
  ('Dimma',     'noun', 'sv'),
  ('Dunge',     'noun', 'sv'),
  ('Ek',        'noun', 'sv'),
  ('Fjäll',     'noun', 'sv'),
  ('Flod',      'noun', 'sv'),
  ('Fors',      'noun', 'sv'),
  ('Gran',      'noun', 'sv'),
  ('Grotta',    'noun', 'sv'),
  ('Hamn',      'noun', 'sv'),
  ('Hed',       'noun', 'sv'),
  ('Holme',     'noun', 'sv'),
  ('Insjö',     'noun', 'sv'),
  ('Kam',       'noun', 'sv'),
  ('Klippa',    'noun', 'sv'),
  ('Koja',      'noun', 'sv'),
  ('Källa',     'noun', 'sv'),
  ('Lykta',     'noun', 'sv'),
  ('Lövskog',   'noun', 'sv'),
  ('Mosse',     'noun', 'sv'),
  ('Näs',       'noun', 'sv'),
  ('Ås',        'noun', 'sv'),
  ('Sjö',       'noun', 'sv'),
  ('Skog',      'noun', 'sv'),
  ('Sluttning', 'noun', 'sv'),
  ('Snår',      'noun', 'sv'),
  ('Stenkil',   'noun', 'sv'),
  ('Strand',    'noun', 'sv'),
  ('Ström',     'noun', 'sv'),
  ('Tall',      'noun', 'sv'),
  ('Torg',      'noun', 'sv'),
  ('Trädgård',  'noun', 'sv'),
  ('Udde',      'noun', 'sv'),
  ('Urskog',    'noun', 'sv'),
  ('Vass',      'noun', 'sv'),
  ('Vattenfall','noun', 'sv'),
  ('Vik',       'noun', 'sv'),
  ('Kust',      'noun', 'sv');
